version: '3'

services:
  toread:
    build: .
    restart: always
    networks:
      - web 
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    labels:
      - traefik.http.routers.dashboard.rule=Host(`toread.deimel.de`)
      - traefik.http.services.dashboard.loadbalancer.server.port=${PORT}
networks:
  web:
    external: true
