version: '3'

services:
  toread:
    build: .
    restart: always
    networks:
      - web 
    ports:
      - "3001:3000"
    env_file:
      - .env
    labels:
      - traefik.http.routers.dashboard.rule=Host(`toread.deimel.de`)
networks:
  web:
    external: true
